######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "Easy-Quizzz | Todas as informações sobre questionários de carta de condução, testes de competição e testes militares."
theme = "liva-hugo-master"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "Di"
URL = "about/"
weight = 1

[[menu.main]]
name = "Enviar"
URL = "blog/"
weight = 2

[[menu.main]]
name = "Contato"
URL = "contact/"
weight = 3

# footer menu
[[menu.footer]]
name = "De"
URL = "about/"
weight = 1

[[menu.footer]]
name = "Enviar"
URL = "blog/"
weight = 2

[[menu.footer]]
name = "Contato"
URL = "contact/"
weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Todas as informações sobre questionários de carta de condução, testes de competição e testes militares."
author = "Rana"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = ""
email = ""
location = ""
# copyright
copyright = "| copyright &copy; 2022 Easy-Quizzz All Rights Reserved |"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Inscreva-se no nosso boletim"
content = ""


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"
